#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2025.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sat May 09 07:06:04 CEST 2026
# SW Build 6299465 on Fri Nov 14 12:34:56 MST 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
export SIM_VER_XSIM=2025.2
export GCC_VER_XSIM=9.3.0

# catch pipeline exit status
set -Eeuo pipefail
# simulate design
echo "xsim TOP_RISCV_tb_behav -key {Behavioral:sim_1:Functional:TOP_RISCV_tb} -tclbatch TOP_RISCV_tb.tcl -view /home/andjelko/Desktop/AMS/RISC-V_pipeline/pipeline_pojekat_1/TOP_RISCV_tb_behav.wcfg -view /home/andjelko/Desktop/AMS/RISC-V_pipeline/pipeline_pojekat_1/Data_path_tb_behav.wcfg -view /home/andjelko/Desktop/AMS/RISC-V_pipeline/pipeline_pojekat_1/Control_path_tb_behav.wcfg -view /home/andjelko/Desktop/AMS/RISC-V_pipeline/pipeline_pojekat_1/RISCV_core_tb_behav.wcfg -log simulate.log"
xsim TOP_RISCV_tb_behav -key {Behavioral:sim_1:Functional:TOP_RISCV_tb} -tclbatch TOP_RISCV_tb.tcl -view /home/andjelko/Desktop/AMS/RISC-V_pipeline/pipeline_pojekat_1/TOP_RISCV_tb_behav.wcfg -view /home/andjelko/Desktop/AMS/RISC-V_pipeline/pipeline_pojekat_1/Data_path_tb_behav.wcfg -view /home/andjelko/Desktop/AMS/RISC-V_pipeline/pipeline_pojekat_1/Control_path_tb_behav.wcfg -view /home/andjelko/Desktop/AMS/RISC-V_pipeline/pipeline_pojekat_1/RISCV_core_tb_behav.wcfg -log simulate.log

